name: ddls_hackathon
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - jupyterlab
  - numpy<2
  - huggingface_hub
  - scikit-image
  - dask
  - umap-learn
  - imagecodecs
  - zarr
  - pythae
  - lightning-bolts
  - pip:
    - -r requirements.txt