name: ddls_hackathon
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - jupyterlab
  - numpy
  - huggingface_hub
  - scikit-image
  - dask
  - umap-learn
  - imagecodecs
  - zarr
  - pip:
    - -r requirements.txt